### ISSUE TITLE
Tenable process stack traces when no ENVs are provided

### ISSUE THREAD

**Issue by claudijd** [mozilla/vautomator-standalone#25]
ERROR:tenable_io:{"reason": "Not Found", "method": "GET", "status_code": 404, "response_headers": {"X-Gateway-Site-ID": "ip-10-1-67-106", "X-Request-Uuid": "4dcba0388b93b32605d7807318f5a820"}, "url": "/scans/228/history/228"}
Traceback (most recent call last):
  File "./run.py", line 114, in <module>
    main()
  File "./run.py", line 110, in main
    runVA(va_scan, output_path)
  File "./run.py", line 74, in runVA
    results = scan_with_tasks.runTasks()
  File "/app/vautomator/lib/target.py", line 154, in runTasks
    if task.NessusTask(self.targetname).checkScanStatus(fresh_nessus) == "COMPLETE":
  File "/app/vautomator/lib/task.py", line 306, in checkScanStatus
    status = nscan.status(nscan.id)
  File "/usr/local/lib/python3.5/dist-packages/tenable_io/helpers/scan.py", line 544, in status
    status = self._client.scans_api.history(self.id, history_id=history_id).status
  File "/usr/local/lib/python3.5/dist-packages/tenable_io/api/scans.py", line 125, in history
    path_params={'scan_id': scan_id, 'history_id': history_id})
  File "/usr/local/lib/python3.5/dist-packages/tenable_io/client.py", line 162, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tenable_io/client.py", line 183, in wrapper
    raise TenableIOApiException(response)
tenable_io.exceptions.TenableIOApiException: {"error":"The requested file was not found"}

**Comment by caggle** [comment]
I believe I fixed this in another PR: https://github.com/mozilla/vautomator-standalone/pull/23 however it's not merged yet (I take full responsibility for it).

I will create another small PR just to fix this so it would not depend on the above PR/feature.

**Comment by caggle** [comment]
PR to fix this: https://github.com/mozilla/vautomator-standalone/pull/33
