### ISSUE TITLE
WebSearch Feature is stack tracing

### ISSUE THREAD

**Issue by claudijd** [mozilla/vautomator-standalone#31]
$ make scan TARGET=REDACTED
docker run -v /Users/jclaudius/code/vautomator-standalone/results:/app/results -it vautomator:latest ./run.py REDACTED
[297e08bdae88] 2019-04-05 02:31:57 PM UTC INFO     [+] Running all the scans now. This may take a while...
[297e08bdae88] 2019-04-05 02:32:08 PM UTC INFO     [+] Tenable.io scan kicked off.
[297e08bdae88] 2019-04-05 02:32:08 PM UTC INFO     [+] Running nmap port scans...
[297e08bdae88] 2019-04-05 02:34:24 PM UTC INFO     [+] Nmap port scan(s) successfully ran.
[297e08bdae88] 2019-04-05 02:34:24 PM UTC INFO     [+] Running WebSearch scan...
Traceback (most recent call last):
  File "./run.py", line 120, in <module>
    main()
  File "./run.py", line 116, in main
    runVA(va_scan, output_path)
  File "./run.py", line 80, in runVA
    results = scan_with_tasks.runTasks()
  File "/app/vautomator/lib/target.py", line 137, in runTasks
    websearch_results = one_task.runWebSearchScan()
  File "/app/vautomator/lib/task.py", line 59, in runWebSearchScan
    for m in googlesearch.search(query="{} security -site:{}".format(self.tasktarget.targetdomain), num=15):
IndexError: tuple index out of range
make: *** [scan] Error 1

**Comment by gdestuynder** [comment]
@claudijd if you want, pm me your REDACTED address, im guessing its something in the results that googlesearch doesnt like but i'd like to confirm - mainly because that would mean "try except pass"

**Comment by gdestuynder** [comment]
I couldn't reproduce with the REDACTED address, then noticed a format string typo - must have had an older untypoed container somehow

**Comment by claudijd** [comment]
@gdestuynder note I was pulling from origin master and make build'ing before filing this bug.  I also tried again when I found the second instance of this.

**Comment by claudijd** [comment]
Rebuilt and it works now...

$ make scan TARGET=REDACTED
docker run -v /Users/jclaudius/code/vautomator-standalone/results:/app/results -it vautomator:latest ./run.py REDACTED
[206a5db8cf0e] 2019-04-09 07:45:50 PM UTC INFO     [+] Running all the scans now. This may take a while...
[206a5db8cf0e] 2019-04-09 07:45:53 PM UTC WARNING  [!] The target has recently been scanned by Tenable.io, retrieving results...
[206a5db8cf0e] 2019-04-09 07:45:57 PM UTC INFO     [+] Tenable.io scan kicked off.
[206a5db8cf0e] 2019-04-09 07:45:57 PM UTC INFO     [+] Running nmap port scans...
[206a5db8cf0e] 2019-04-09 07:48:18 PM UTC INFO     [+] Nmap port scan(s) successfully ran.
[206a5db8cf0e] 2019-04-09 07:48:18 PM UTC INFO     [+] Running WebSearch scan...
[206a5db8cf0e] 2019-04-09 07:48:21 PM UTC INFO     [+] WebSearch scan successfully ran.
[206a5db8cf0e] 2019-04-09 07:48:21 PM UTC INFO     [+] Running HTTP Observatory scan...
[206a5db8cf0e] 2019-04-09 07:48:24 PM UTC INFO     [+] HTTP Observatory scan successfully ran.
[206a5db8cf0e] 2019-04-09 07:48:24 PM UTC INFO     [+] Running TLS Observatory scan...
[206a5db8cf0e] 2019-04-09 07:48:37 PM UTC INFO     [+] TLS Observatory scan successfully ran.
[206a5db8cf0e] 2019-04-09 07:48:37 PM UTC INFO     [+] Running dirb scan...

**Comment by gdestuynder** [comment]
@claudijd i meant that I must have had an older container which is why mine worked - yours was correctly failing -  the pr fixed that
